platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/_@capacitor_ios@3.3.2@@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/_@capacitor_ios@3.3.2@@capacitor/ios'
  pod 'CapacitorApp', :path => '..\..\node_modules\_@capacitor_app@1.0.6@@capacitor\app'
  pod 'CapacitorHaptics', :path => '..\..\node_modules\_@capacitor_haptics@1.1.3@@capacitor\haptics'
  pod 'CapacitorKeyboard', :path => '..\..\node_modules\_@capacitor_keyboard@1.1.3@@capacitor\keyboard'
  pod 'CapacitorStatusBar', :path => '..\..\node_modules\_@capacitor_status-bar@1.0.6@@capacitor\status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
